// Copyright (c) 2023-2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: session-dsm.proto

package sessiondsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTerminateGameSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTerminateGameSession) Reset() {
	*x = RequestTerminateGameSession{}
	mi := &file_session_dsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTerminateGameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTerminateGameSession) ProtoMessage() {}

func (x *RequestTerminateGameSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_dsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTerminateGameSession.ProtoReflect.Descriptor instead.
func (*RequestTerminateGameSession) Descriptor() ([]byte, []int) {
	return file_session_dsm_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTerminateGameSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestTerminateGameSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RequestTerminateGameSession) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type ResponseTerminateGameSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseTerminateGameSession) Reset() {
	*x = ResponseTerminateGameSession{}
	mi := &file_session_dsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseTerminateGameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTerminateGameSession) ProtoMessage() {}

func (x *ResponseTerminateGameSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_dsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTerminateGameSession.ProtoReflect.Descriptor instead.
func (*ResponseTerminateGameSession) Descriptor() ([]byte, []int) {
	return file_session_dsm_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseTerminateGameSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResponseTerminateGameSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResponseTerminateGameSession) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseTerminateGameSession) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RequestCreateGameSession struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployment      string                 `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	SessionData     string                 `protobuf:"bytes,4,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	RequestedRegion []string               `protobuf:"bytes,5,rep,name=requested_region,json=requestedRegion,proto3" json:"requested_region,omitempty"`
	MaximumPlayer   int64                  `protobuf:"varint,6,opt,name=maximum_player,json=maximumPlayer,proto3" json:"maximum_player,omitempty"`
	ClientVersion   string                 `protobuf:"bytes,7,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	GameMode        string                 `protobuf:"bytes,8,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	Secret          string                 `protobuf:"bytes,9,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestCreateGameSession) Reset() {
	*x = RequestCreateGameSession{}
	mi := &file_session_dsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateGameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateGameSession) ProtoMessage() {}

func (x *RequestCreateGameSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_dsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateGameSession.ProtoReflect.Descriptor instead.
func (*RequestCreateGameSession) Descriptor() ([]byte, []int) {
	return file_session_dsm_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCreateGameSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestCreateGameSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RequestCreateGameSession) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *RequestCreateGameSession) GetSessionData() string {
	if x != nil {
		return x.SessionData
	}
	return ""
}

func (x *RequestCreateGameSession) GetRequestedRegion() []string {
	if x != nil {
		return x.RequestedRegion
	}
	return nil
}

func (x *RequestCreateGameSession) GetMaximumPlayer() int64 {
	if x != nil {
		return x.MaximumPlayer
	}
	return 0
}

func (x *RequestCreateGameSession) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *RequestCreateGameSession) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *RequestCreateGameSession) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ResponseCreateGameSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SessionData   string                 `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int64                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	ServerId      string                 `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Deployment    string                 `protobuf:"bytes,9,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Region        string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	ClientVersion string                 `protobuf:"bytes,11,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	GameMode      string                 `protobuf:"bytes,12,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	CreatedRegion string                 `protobuf:"bytes,13,opt,name=created_region,json=createdRegion,proto3" json:"created_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateGameSession) Reset() {
	*x = ResponseCreateGameSession{}
	mi := &file_session_dsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateGameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateGameSession) ProtoMessage() {}

func (x *ResponseCreateGameSession) ProtoReflect() protoreflect.Message {
	mi := &file_session_dsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateGameSession.ProtoReflect.Descriptor instead.
func (*ResponseCreateGameSession) Descriptor() ([]byte, []int) {
	return file_session_dsm_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseCreateGameSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResponseCreateGameSession) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResponseCreateGameSession) GetSessionData() string {
	if x != nil {
		return x.SessionData
	}
	return ""
}

func (x *ResponseCreateGameSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResponseCreateGameSession) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ResponseCreateGameSession) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ResponseCreateGameSession) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ResponseCreateGameSession) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResponseCreateGameSession) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ResponseCreateGameSession) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ResponseCreateGameSession) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ResponseCreateGameSession) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *ResponseCreateGameSession) GetCreatedRegion() string {
	if x != nil {
		return x.CreatedRegion
	}
	return ""
}

type ResponseCreateGameSessionAsync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateGameSessionAsync) Reset() {
	*x = ResponseCreateGameSessionAsync{}
	mi := &file_session_dsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateGameSessionAsync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateGameSessionAsync) ProtoMessage() {}

func (x *ResponseCreateGameSessionAsync) ProtoReflect() protoreflect.Message {
	mi := &file_session_dsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateGameSessionAsync.ProtoReflect.Descriptor instead.
func (*ResponseCreateGameSessionAsync) Descriptor() ([]byte, []int) {
	return file_session_dsm_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseCreateGameSessionAsync) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseCreateGameSessionAsync) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_session_dsm_proto protoreflect.FileDescriptor

const file_session_dsm_proto_rawDesc = "" +
	"\n" +
	"\x11session-dsm.proto\x12\x1caccelbyte.session.sessiondsm\"n\n" +
	"\x1bRequestTerminateGameSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\"\x8d\x01\n" +
	"\x1cResponseTerminateGameSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xc8\x02\n" +
	"\x18RequestCreateGameSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"deployment\x18\x03 \x01(\tR\n" +
	"deployment\x12!\n" +
	"\fsession_data\x18\x04 \x01(\tR\vsessionData\x12)\n" +
	"\x10requested_region\x18\x05 \x03(\tR\x0frequestedRegion\x12%\n" +
	"\x0emaximum_player\x18\x06 \x01(\x03R\rmaximumPlayer\x12%\n" +
	"\x0eclient_version\x18\a \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tgame_mode\x18\b \x01(\tR\bgameMode\x12\x16\n" +
	"\x06secret\x18\t \x01(\tR\x06secret\"\x8f\x03\n" +
	"\x19ResponseCreateGameSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fsession_data\x18\x03 \x01(\tR\vsessionData\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x03R\x04port\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\tR\bserverId\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"deployment\x18\t \x01(\tR\n" +
	"deployment\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12%\n" +
	"\x0eclient_version\x18\v \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tgame_mode\x18\f \x01(\tR\bgameMode\x12%\n" +
	"\x0ecreated_region\x18\r \x01(\tR\rcreatedRegion\"T\n" +
	"\x1eResponseCreateGameSessionAsync\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb4\x03\n" +
	"\n" +
	"SessionDsm\x12\x84\x01\n" +
	"\x11CreateGameSession\x126.accelbyte.session.sessiondsm.RequestCreateGameSession\x1a7.accelbyte.session.sessiondsm.ResponseCreateGameSession\x12\x8d\x01\n" +
	"\x14TerminateGameSession\x129.accelbyte.session.sessiondsm.RequestTerminateGameSession\x1a:.accelbyte.session.sessiondsm.ResponseTerminateGameSession\x12\x8e\x01\n" +
	"\x16CreateGameSessionAsync\x126.accelbyte.session.sessiondsm.RequestCreateGameSession\x1a<.accelbyte.session.sessiondsm.ResponseCreateGameSessionAsyncBe\n" +
	" net.accelbyte.session.sessiondsmP\x01Z accelbyte.net/session/sessiondsm\xaa\x02\x1cAccelByte.Session.SessionDsmb\x06proto3"

var (
	file_session_dsm_proto_rawDescOnce sync.Once
	file_session_dsm_proto_rawDescData []byte
)

func file_session_dsm_proto_rawDescGZIP() []byte {
	file_session_dsm_proto_rawDescOnce.Do(func() {
		file_session_dsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_dsm_proto_rawDesc), len(file_session_dsm_proto_rawDesc)))
	})
	return file_session_dsm_proto_rawDescData
}

var file_session_dsm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_session_dsm_proto_goTypes = []any{
	(*RequestTerminateGameSession)(nil),    // 0: accelbyte.session.sessiondsm.RequestTerminateGameSession
	(*ResponseTerminateGameSession)(nil),   // 1: accelbyte.session.sessiondsm.ResponseTerminateGameSession
	(*RequestCreateGameSession)(nil),       // 2: accelbyte.session.sessiondsm.RequestCreateGameSession
	(*ResponseCreateGameSession)(nil),      // 3: accelbyte.session.sessiondsm.ResponseCreateGameSession
	(*ResponseCreateGameSessionAsync)(nil), // 4: accelbyte.session.sessiondsm.ResponseCreateGameSessionAsync
}
var file_session_dsm_proto_depIdxs = []int32{
	2, // 0: accelbyte.session.sessiondsm.SessionDsm.CreateGameSession:input_type -> accelbyte.session.sessiondsm.RequestCreateGameSession
	0, // 1: accelbyte.session.sessiondsm.SessionDsm.TerminateGameSession:input_type -> accelbyte.session.sessiondsm.RequestTerminateGameSession
	2, // 2: accelbyte.session.sessiondsm.SessionDsm.CreateGameSessionAsync:input_type -> accelbyte.session.sessiondsm.RequestCreateGameSession
	3, // 3: accelbyte.session.sessiondsm.SessionDsm.CreateGameSession:output_type -> accelbyte.session.sessiondsm.ResponseCreateGameSession
	1, // 4: accelbyte.session.sessiondsm.SessionDsm.TerminateGameSession:output_type -> accelbyte.session.sessiondsm.ResponseTerminateGameSession
	4, // 5: accelbyte.session.sessiondsm.SessionDsm.CreateGameSessionAsync:output_type -> accelbyte.session.sessiondsm.ResponseCreateGameSessionAsync
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_session_dsm_proto_init() }
func file_session_dsm_proto_init() {
	if File_session_dsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_dsm_proto_rawDesc), len(file_session_dsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_dsm_proto_goTypes,
		DependencyIndexes: file_session_dsm_proto_depIdxs,
		MessageInfos:      file_session_dsm_proto_msgTypes,
	}.Build()
	File_session_dsm_proto = out.File
	file_session_dsm_proto_goTypes = nil
	file_session_dsm_proto_depIdxs = nil
}
